title: QA Sampa Meeting
description: QA Sampa Meeting

url: http://qasampameeting.github.io
baseurl: ""

markdown: kramdown
highlighter: rouge

navigation:
 - title: sobre
   url: /about
 - title: eventos
   url: /events
 - title: palestrantes
   url: /speakers
 - title: equipe
   url: /team
 - title: contato
   url: /contact


# EVENTS
events:
  abril:
    - date: 13-04-2018
      title: Workshop-Git para iniciantes
      name: Débora Fernande
      local: Campus Code
      link: https://www.eventbrite.com.br/e/git-para-iniciantes-inscricoes-a-partir-do-dia-06-04-as-23h-registration-44058287524

    - date: 13-04-2018
      title: "Testes de performance: Por onde começar?"
      name: Alan Gularte
      local: ThoughtWorks
      link: https://www.eventbrite.com.br/e/testes-de-performance-para-aplicacoes-web-por-onde-comecar-inscricoes-a-partir-do-dia-06-04-as-23h-registration-44833632602

    - date: 19-04-2018
      title: Hackers QA-encontro para codarmos junto
      name:  Todos nós
      local: Creditas
      link: https://www.eventbrite.com.br/e/hackers-qa-inscricoes-a-partir-do-dia-14-04-as-23h-registration-44512733785

    - date: 26-04-2018
      title: Workshop-Por que testar APIs?
      name: Samuel e Nathanael
      local: Caelum
      link: https://www.eventbrite.com.br/e/por-que-testar-apis-inscricoes-a-partir-do-dia-19-04-as-23h-registration-43291305460

  maio:
    - date: 10-05-2018
      title: Workshop-Testes de Performance
      name: Júlio de Lima
      local: Caelum
      link: https://www.eventbrite.com.br/e/testes-de-performance-inscricoes-a-partir-do-dia-02-05-as-23h-registration-43731000600

    - date: 24-05-2018
      title: Workshop-Test Driven Development - TDD
      name: Camila e Júlia
      local: Caelum
      link: https://www.eventbrite.com.br/e/test-driven-development-tdd-inscricoes-a-partir-do-dia-17-05-as-23h-registration-43732427869

  junho:
    - date: 13-06-2018
      title: Workshop-Por que utilizar BDD?
      name: Fernando Papito
      local: Moip
      link: https://www.eventbrite.com.br/e/por-que-utilizar-bdd-inscricoes-a-partir-do-dia-06-06-as-23h-registration-43291769849
  
    - date: 27-06-2018
      title: Visual Regression Testing
      name: Samanta Cicilia
      local: Moip

  julho:
    - date: Data a definir
      title: Automação com Appium
      name: Thialison e Darling
      local: a definir

  

# SPEAKERS
speakers:
  - name: Débora Fernande
    image: debora-fernandes.jpg
    link: https://www.linkedin.com/in/debborafernandess/

  - name: Alan Gularte
    image: alan-gularte.jpg
    link: https://www.linkedin.com/in/alancafrunigularte/

  - name: Nathanael Araújo
    image: nathanael-araujo.jpg
    link: https://www.linkedin.com/in/nathanaelaraujo

  - name: Samuel Pereira
    image: samuel-pereira.jpg
    link: https://www.linkedin.com/in/samuel-pereira-68327b23

  - name: Júlio de Lima
    image: julio-lima.jpg
    link: https://www.linkedin.com/in/juliodelimas/

  - name: Camila Campos
    image: camila-campos.jpg
    link: https://www.linkedin.com/in/camilacamposramos/

  - name: Júlia Birkett
    image: julia-birkett.jpg
    link: https://www.linkedin.com/in/birkettjulia/

  - name: Fernando Papito
    image: fernando-papito.jpg
    link: https://www.linkedin.com/in/papitoio/

  - name: Samanta Cicilia
    image: samanta-cicilia.jpg
    link: https://www.linkedin.com/in/samantacici/

  - name: Thialison Souza
    image: thialison-souza.jpg
    link: https://www.linkedin.com/in/thialisontester/

  - name: Darling Cabral
    image: darling-cabral.jpg
    link: https://www.linkedin.com/in/darling-cabral-6b709a49/

  - name: Rodrigo Matola
    image: rodrigo-matola.jpg
    link: https://www.linkedin.com/in/rodrigomatola/

  - name: Karoline Leite
    image: karoline-leite.jpg
    link: https://www.linkedin.com/in/karolxavierleite

  - name: Wellington Avelin
    image: wellington-avelino.jpg
    link: https://www.linkedin.com/in/wellington-avelino

# TEAM
team:
  - name: Carla Crude
    role: founder
    image: carla-crude.jpg
    link: https://about.me/carla_crude
    link_text: about.me/carla_crude

  - name: Guilherme Cruz
    role: co-founder
    image: guilherme-cruz.jpg
    link: http://gcruz.com.br
    link_text: gcruz.com.br

  - name: Charles Kilesse
    role: organization
    image: charles-kilesse.jpg
    link: https://www.linkedin.com/in/ckilesse/
    link_text: linkedin.com/ckilesse/

  - name: Rafael Grassi
    role: organization
    image: rafael-grassi.jpg
    link: https://www.linkedin.com/in/rafael-grassi-ribon-2797b4b2/
    link_text: linkedin/rafael-grassi-ribon

  - name: Luna Ticeu
    role: organization
    image: luna-ticeu.jpg
    link: https://www.linkedin.com/in/luna-ticeu-ctfl-ctfl-at-373a95104/
    link_text: linkedin/luna-ticeu

  - name: Nathália Freire
    role: organization
    image: nathalia-freire.jpg
    link: https://www.linkedin.com/in/nathalia-freire-43620331/
    link_text: linkedin/nathalia-freire

  - name: Maico Santos
    role: organization
    image: maico-santos.jpg
    link: https://www.linkedin.com/in/maico-santos-8470031a/
    link_text: linkedin/maico-santos

  - name: Rafael Amaral
    role: organization
    image: rafael-amaral.jpg
    link: https://www.linkedin.com/in/amaralrfl/
    link_text: linkedin/rafael-amaral

  - name: Bruna Rosa
    role: organization
    image: bruna-rosa.jpg
    link: https://www.linkedin.com/in/bruna-rosa-qa/
    link_text: linkedin/bruna-rosa

    

# SOCIAL MEDIA
social:
  meetup: https://www.meetup.com/pt-BR/qasampameeting
  linkedin: https://www.linkedin.com/company/qasampameeting
  facebook: https://www.facebook.com/qasampameeting
  youtube: https://www.youtube.com/c/QASampaMeeting
  twitter: https://twitter.com/qasampameeting
  instagram: https://www.instagram.com/qasampameeting

sponsors:
  thoughtworks: https://www.thoughtworks.com/pt
  campuscode: https://campuscode.com.br
  caelum: https://www.caelum.com.br
  moip: https://moip.com.br/
  giovana: https://www.instagram.com/giovanasantosfotografia
  walkandclick: https://www.facebook.com/walkandclickon

google_analytics: "UA-114034864-1"
