title: QA Sampa Meeting
description: QA Sampa Meeting

url: http://qasampameeting.github.io
baseurl: ""

markdown: kramdown
highlighter: rouge

navigation:
 - title: sobre
   url: /about
 - title: eventos
   url: /events
 - title: palestrantes
   url: /speakers
 - title: equipe
   url: /team
 - title: contato
   url: /contact


# EVENTS
events:
  abril:
    - date: 13-04-2018
      title: Workshop-Git para iniciantes
      link: https://www.eventbrite.com.br/e/git-para-iniciantes-inscricoes-a-partir-do-dia-06-04-as-23h-registration-44058287524

    - date: 19-04-2018
      title: Hackers QA-encontro para codarmos junto
      link: https://www.eventbrite.com.br/e/hackers-qa-inscricoes-a-partir-do-dia-14-04-as-23h-registration-44512733785

    - date: 26-04-2018
      title: Workshop-Por que testar APIs?
      link: https://www.eventbrite.com.br/e/por-que-testar-apis-inscricoes-a-partir-do-dia-19-04-as-23h-registration-43291305460

  maio:
    - date: 10-05-2018
      title: Workshop-Testes de Performance
      link: https://www.eventbrite.com.br/e/testes-de-performance-inscricoes-a-partir-do-dia-02-05-as-23h-registration-43731000600

    - date: 24-05-2018
      title: Workshop-Test Driven Development - TDD
      link: https://www.eventbrite.com.br/e/test-driven-development-tdd-inscricoes-a-partir-do-dia-17-05-as-23h-registration-43732427869

  junho:
    - date: 13-06-2018
      title: Workshop-Por que utilizar BDD?
      link: https://www.eventbrite.com.br/e/por-que-utilizar-bdd-inscricoes-a-partir-do-dia-06-06-as-23h-registration-43291769849


# SPEAKERS
speakers:
  - name: Debora Fernandes
    image: debora-fernandes.jpg
    link: https://www.linkedin.com/in/debborafernandess/

  - name: Nathanael Araújo
    image: nathanael-araujo.jpg
    link: https://www.linkedin.com/in/nathanaelaraujo

  - name: Samuel Pereira
    image: samuel-pereira.jpg
    link: https://www.linkedin.com/in/samuel-pereira-68327b23

  - name: Júlio de Lima
    image: julio-lima.jpg
    link: https://www.linkedin.com/in/juliodelimas/

  - name: Camila Campos
    image: camila-campos.jpg
    link: https://www.linkedin.com/in/camilacamposramos/

  - name: Júlia Birkett
    image: julia-birkett.jpg
    link: https://www.linkedin.com/in/birkettjulia/

  - name: Fernando Papito
    image: fernando-papito.jpg
    link: https://www.linkedin.com/in/papitoio/

  - name: Rodrigo Matola
    image: rodrigo-matola.jpg
    link: https://www.linkedin.com/in/rodrigomatola/

  - name: Karoline Leite
    image: karoline-leite.jpg
    link: https://www.linkedin.com/in/karolxavierleite

  - name: Wellington Avelino
    image: wellington-avelino.jpg
    link: https://www.linkedin.com/in/wellington-avelino

# TEAM
team:
  - name: Carla Crude
    role: founder
    image: carla-crude.jpg
    link: https://about.me/carla_crude
    link_text: about.me/carla_crude

  - name: Guilherme Cruz
    role: co-founder
    image: guilherme-cruz.jpg
    link: http://gcruz.com.br
    link_text: gcruz.com.br

  - name: Charles Kilesse
    role: organization
    image: charles-kilesse.jpg
    link: https://www.linkedin.com/in/ckilesse/
    link_text: linkedin.com/ckilesse/

  - name: Rafael Grassi
    role: organization
    image: rafael-grassi.jpg
    link: https://www.linkedin.com/in/rafael-grassi-ribon-2797b4b2/
    link_text: linkedin/rafael-grassi-ribon

# SOCIAL MEDIA
social:
  meetup: https://www.meetup.com/pt-BR/qasampameeting
  linkedin: https://www.linkedin.com/company/qasampameeting
  facebook: https://www.facebook.com/qasampameeting
  youtube: https://www.youtube.com/c/QASampaMeeting
  twitter: https://twitter.com/qasampameeting
  instagram: https://www.instagram.com/qasampameeting

sponsors:
  thoughtworks: https://www.thoughtworks.com/pt
  campuscode: https://campuscode.com.br
  caelum: https://www.caelum.com.br
  giovana: https://www.instagram.com/giovanasantosfotografia
  walkandclick: https://www.facebook.com/walkandclickon

google_analytics: "UA-114034864-1"
