title: QA Sampa Meeting
description: QA Sampa Meeting

url: http://qasampameeting.github.io
baseurl: ""

markdown: kramdown
highlighter: rouge

navigation:
 - title: sobre
   url: /about
 - title: eventos
   url: /events
 - title: palestrantes
   url: /speakers
 - title: equipe
   url: /team
 - title: contato
   url: /contact


# EVENTS
events:
  março:
    - date: 28-03-2018
      title: Workshop-Comece a automatizar com o Robot Framework
      link: https://www.eventbrite.com.br/e/comece-a-automatizar-com-o-robot-framework-inscricoes-a-partir-do-dia-21-03-as-23h-registration-43290543180

  abril:
    - date: 05-04-2018
      title: Hackers QA-encontro para codarmos junto
      link: https://www.eventbrite.com.br/e/hackers-qa-registration-44512733785
    
    - date: 13-04-2018
      title: Workshop-Git para iniciantes
      link: https://www.eventbrite.com.br/e/git-para-iniciantes-inscricoes-a-partir-do-dia-06-04-as-23h-registration-44058287524

    - date: 26-04-2018
      title: Workshop-Por que testar APIs?
      link: https://www.eventbrite.com.br/e/por-que-testar-apis-inscricoes-a-partir-do-dia-19-04-as-23h-registration-43291305460

  maio:
    - date: 10-05-2018
      title: Workshop-Testes de Performance
      link: https://www.eventbrite.com.br/e/testes-de-performance-inscricoes-a-partir-do-dia-02-05-as-23h-registration-43731000600

    - date: 24-05-2018
      title: Workshop-Test Driven Development - TDD
      link: https://www.eventbrite.com.br/e/test-driven-development-tdd-inscricoes-a-partir-do-dia-17-05-as-23h-registration-43732427869

  junho:
    - date: 13-06-2018
      title: Workshop-Por que utilizar BDD?
      link: https://www.eventbrite.com.br/e/por-que-utilizar-bdd-inscricoes-a-partir-do-dia-06-06-as-23h-registration-43291769849


# SPEAKERS
speakers:
  - name: Rodrigo Matola
    image: rodrigo-matola.jpg
    description: Tenho experiência em garantia de qualidade de software com foco em automação, apoio à equipe, registro e relatórios de erros, além de interface com empresas e clientes. Também possuo experiência em especificação, gerenciamento e comunicação de requisitos de infra-estrutura.
    link: https://www.linkedin.com/in/rodrigomatola/

  - name: Debora Fernandes
    image: debora-fernandes.jpg
    description: Evoluir constantemente aprendendendo e absorvendo novas tecnologias, novas formas de trabalhar e novos conceitos de mercado.
    link: https://www.linkedin.com/in/debborafernandess/

  - name: Nathanael Araújo
    image: nathanael-araujo.jpg
    description: QA Chapter Leader na Concrete Solutions.
    link: https://www.linkedin.com/in/nathanaelaraujo

  - name: Samuel Pereira
    image: samuel-pereira.jpg
    description: QA Chapter Leader na Concrete Solutions
    link: https://www.linkedin.com/in/samuel-pereira-68327b23

  - name: Júlio de Lima
    image: julio-lima.jpg
    description: Senior Consultant na Capco
    link: https://www.linkedin.com/in/juliodelimas/

  - name: Camila Campos
    image: camila-campos.jpg
    description: Software Engineer na Creditas | Organizadora Rails Girls São Paulo e Women Dev Summit
    link: https://www.linkedin.com/in/camilacamposramos/

  - name: Júlia Birkett
    image: julia-birkett.jpg
    description: Software Engineer na Creditas - Adoro a tecnologia e a programação e acho que a melhor maneira de aprender é praticar seu conhecimento!
    link: https://www.linkedin.com/in/birkettjulia/

  - name: Fernando Papito
    image: fernando-papito.jpg
    description: Especialista em testes automatizados e entrega contínua. 15 anos atuando em testes e implantação de software em empresas do segmento financeiro, telecomunicações, marketing digital e programas de fidelização de clientes.
    link: https://www.linkedin.com/in/papitoio/

  - name: Karoline Leite
    image: karoline-leite.jpg
    description: Mais de 9 anos de experiência trabalhando com garantia de qualidade de software e testes. Nos últimos anos, concentrei minha carreira em testar técnicas de automação e teste de desempenho, bem como práticas e metodologias ágeis.
    link: https://www.linkedin.com/in/karolxavierleite

  - name: Wellington Avelino
    image: wellington-avelino.jpg
    description: Profissional formado em análise e desenvolvimento de sistemas, com fortes conhecimentos em desenvolvimento mobile e web, atualmente trabalho como QA desenvolvendo especificações vivas do sistema, também sou grande entusiasta de especificação por exemplo e metodologias ágeis.
    link: https://www.linkedin.com/in/wellington-avelino

# SOCIAL MEDIA
social:
  meetup: https://www.meetup.com/pt-BR/qasampameeting
  linkedin: https://www.linkedin.com/company/qasampameeting
  facebook: https://www.facebook.com/qasampameeting
  youtube: https://www.youtube.com/channel/UCGq0B659AiKi58KYl0ubllw?view_as=subscriber
  twitter: https://twitter.com/qasampameeting
  instagram: https://www.instagram.com/qasampameeting

sponsors:
  thoughtworks: https://www.thoughtworks.com/pt
  campuscode: https://campuscode.com.br
  caelum: https://www.caelum.com.br
  giovana: https://www.instagram.com/giovanasantosfotografia
  walkandclick: https://www.facebook.com/walkandclickon

google_analytics: "UA-114034864-1"
