title: QA Sampa Meeting
description: QA Sampa Meeting

url: http://qasampameeting.github.io
baseurl: ""

markdown: kramdown
highlighter: rouge

navigation:
 - title: sobre
   url: /about
 - title: eventos
   url: /events
 - title: palestrantes
   url: /speakers
 - title: equipe
   url: /team
 - title: contato
   url: /contact


# EVENTS
events:
  fevereiro:
    date: 22-02-2018
    title: O papel do QA na Integração Contínua
    link: https://www.meetup.com/pt-BR/qasampameeting/events/cqvphpyxfbcc
  março:
    date: 16-03-2018
    title: Automação de testes em front-end
    link: https://www.meetup.com/pt-BR/qasampameeting/events/247575648
  abril:
    date: 26-04-2018
    title: Por que testar APIs?

# SPEAKERS
speakers:
  - name: Wellington Avelino
    image: wellington-avelino.jpg
    description: Profissional formado em análise e desenvolvimento de sistemas, com fortes conhecimentos em desenvolvimento mobile e web, atualmente trabalho como QA desenvolvendo especificações vivas do sistema, também sou grande entusiasta de especificação por exemplo e metodologias ágeis.
    link: https://www.linkedin.com/in/wellington-avelino
  - name: Karoline Leite
    image: karoline-leite.jpg
    description: Mais de 9 anos de experiência trabalhando com garantia de qualidade de software e testes. Nos últimos anos, concentrei minha carreira em testar técnicas de automação e teste de desempenho, bem como práticas e metodologias ágeis.
    link: https://www.linkedin.com/in/karolxavierleite
  - name: Nathanael Araújo
    image: nathanael-araujo.jpg
    description: QA Chapter Leader na Concrete Solutions.
    link: https://www.linkedin.com/in/nathanaelaraujo
  - name: Samuel Pereira
    image: samuel-pereira.jpg
    description: QA Chapter Leader na Concrete Solutions
    link: https://www.linkedin.com/in/samuel-pereira-68327b23
  - name: Rodrigo Matola
    image: rodrigo-matola.jpg
    description: Tenho experiência em garantia de qualidade de software com foco em automação, apoio à equipe, registro e relatórios de erros, além de interface com empresas e clientes. Também possuo experiência em especificação, gerenciamento e comunicação de requisitos de infra-estrutura.
    link: https://www.linkedin.com/in/rodrigomatola/

# SOCIAL MEDIA
social:
  meetup: https://www.meetup.com/pt-BR/qasampameeting
  linkedin: https://www.linkedin.com/company/qasampameeting
  facebook: https://www.facebook.com/qasampameeting
  youtube: https://www.youtube.com/channel/UCGq0B659AiKi58KYl0ubllw?view_as=subscriber
  twitter: https://twitter.com/qasampameeting
  instagram: https://www.instagram.com/qasampameeting

sponsors:
  thoughtworks: https://www.thoughtworks.com/pt
  campuscode: https://campuscode.com.br
  caelum: https://www.caelum.com.br
  giovana: https://www.instagram.com/giovanasantosfotografia

google_analytics: "UA-114034864-1"
