title: QA Sampa Meeting
description: QA Sampa Meeting

url: http://qasampameeting.github.io
baseurl: ""

markdown: kramdown
highlighter: rouge

navigation:
 - title: sobre
   url: /about
 - title: eventos
   url: /events
 - title: palestrantes
   url: /speakers
 - title: equipe
   url: /team
 - title: contato
   url: /contact

# SOCIAL MEDIA
social:
  meetup: https://www.meetup.com/pt-BR/qasampameeting
  slack: https://join.slack.com/t/qasampameeting/shared_invite/enQtMzUwOTYwNzYyNzM4LTU0YWNjYzQ5YjMxZDA0YTViZWRkMTJkZjJiMmRkYzJjZmJmMjEzNTBhY2Y5MDEzY2RkNmNjMjZjOTYwMjg5ODc
  facebook: https://www.facebook.com/qasampameeting
  linkedin: https://www.linkedin.com/company/qasampameeting
  twitter: https://twitter.com/qasampameeting
  instagram: https://www.instagram.com/qasampameeting
  youtube: https://www.youtube.com/c/QASampaMeeting
  medium: https://medium.com/qa-sampa-meeting

google_analytics: "UA-114034864-1"
